### ISSUE TITLE
Bookmarking sites that require a certain user-agent string causes unwanted behavior.

### ISSUE THREAD

**Issue by lxe** [lxe/clickbin#5]
For example, adding "facebook.com" to a  bin, causes the title to be "Update Your Browser | Facebook"

**Comment by vicapow** [comment]
+1

**Comment by vicapow** [comment]
can't really deal with until jsdom fixes it or we submit a patch to them: https://github.com/tmpvar/jsdom/issues/196

**Comment by vicapow** [comment]
see: https://github.com/lxe/clickbin/commit/d96d551c19e36c127d5007b1a978c993d19eb848
